# Generated by Django 2.1.2 on 2018-10-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='camtelclient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(verbose_name='date/time')),
                ('Inbound', models.CharField(max_length=200)),
                ('col2_cdefa', models.CharField(max_length=200)),
                ('Outbound', models.CharField(max_length=200)),
                ('col4_cdeff', models.CharField(max_length=200)),
                ('col5_cdefa', models.CharField(max_length=200)),
                ('col6_cdefbb', models.CharField(max_length=200)),
            ],
        ),
    ]
