# Generated by Django 2.1.2 on 2018-10-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camtelclient',
            name='Inbound',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='camtelclient',
            name='Outbound',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='camtelclient',
            name='col2_cdefa',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='camtelclient',
            name='col4_cdeff',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='camtelclient',
            name='col5_cdefa',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='camtelclient',
            name='col6_cdefbb',
            field=models.CharField(max_length=500),
        ),
    ]
