# Generated by Django 2.1.2 on 2018-10-17 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='output',
            name='DateDeRetablisement',
        ),
        migrations.RemoveField(
            model_name='output',
            name='Duree',
        ),
        migrations.RemoveField(
            model_name='output',
            name='Number',
        ),
        migrations.RemoveField(
            model_name='output',
            name='camtel',
        ),
        migrations.RemoveField(
            model_name='output',
            name='client',
        ),
        migrations.RemoveField(
            model_name='output',
            name='observation',
        ),
        migrations.AddField(
            model_name='output',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camtelclient',
            name='Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='camtelclient',
            name='Inbound',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='camtelclient',
            name='Outbound',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='camtelclient',
            name='col2_cdefa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='camtelclient',
            name='col4_cdeff',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='camtelclient',
            name='col5_cdefa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='camtelclient',
            name='col6_cdefbb',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='output',
            name='DateDeCoupure',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
