# Generated by Django 2.1.2 on 2018-10-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20181017_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='DateDeRetablisement',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
