# Generated by Django 2.1.2 on 2018-10-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_output_datederetablisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='Duree',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
