# Generated by Django 2.1.2 on 2018-10-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20181019_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='Duree',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
