# Generated by Django 2.1.2 on 2018-10-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20181019_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='Duree',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
