# Generated by Django 2.1.2 on 2018-10-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20181019_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='Duree',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
