# Generated by Django 2.1.2 on 2018-10-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20181019_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='output',
            name='Duree',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
