# Generated by Django 2.1.2 on 2018-10-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20181019_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
