# Generated by Django 2.1.2 on 2018-10-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_output_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='camtel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='client',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
