# Generated by Django 2.1.2 on 2018-10-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20181019_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='output',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
