# Generated by Django 2.1.2 on 2018-10-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20181030_1856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='title',
        ),
        migrations.AddField(
            model_name='output',
            name='Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
