# Generated by Django 2.1.2 on 2018-11-02 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20181030_1936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='camtelclient',
        ),
    ]
